% palabras a eliminar
to_clean("o").
to_clean("os").
to_clean("as").
to_clean("un").
to_clean("una").
to_clean("uno").
to_clean("unas").
to_clean("unos").
to_clean("a").
to_clean("ante").
to_clean("bajo").
to_clean("cabe").
to_clean("con").
to_clean("contra").
to_clean("de").
to_clean("del").
to_clean("desde").
to_clean("durante").
to_clean("en").
to_clean("entre").
to_clean("hacia").
to_clean("hasta").
to_clean("mediante").
to_clean("para").
to_clean("por").
to_clean("segun").
to_clean("sin").
to_clean("so").
to_clean("sobre").
to_clean("tras").
to_clean("el").
to_clean("lo").
to_clean("la").
to_clean("los").
to_clean("las").
to_clean("un").
to_clean("uno").
to_clean("una").
to_clean("unos").
to_clean("unas").
to_clean("este").
to_clean("esta").
to_clean("estos").
to_clean("estas").
to_clean("ese").
to_clean("esa").
to_clean("esos").
to_clean("esas").
to_clean("aquel").
to_clean("aquella").
to_clean("aquellos").
to_clean("aquellas").
to_clean("mi").
to_clean("mis").
to_clean("tu").
to_clean("tus").
to_clean("su").
to_clean("sus").
to_clean("se").
to_clean("que").
to_clean("quien").
to_clean("quienes").
to_clean("cuan").
to_clean("cual").
to_clean("cuales").
to_clean("donde").
